CREATE TABLE IF NOT EXISTS rawdata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL,
    url VARCHAR(2000) NOT NULL,
    final_url VARCHAR(2000),
    http_status INTEGER,
    raw_object_key VARCHAR(1000),
    raw_payload_type VARCHAR(100),
    raw_content_hash VARCHAR(64),
    crawl_run_id UUID NOT NULL DEFAULT gen_random_uuid(),
    status VARCHAR(50) NOT NULL,
    error_type VARCHAR(100),
    error_message TEXT,
    fetched_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_rawdata_source_id
    ON rawdata (source_id);

CREATE INDEX IF NOT EXISTS idx_rawdata_status
    ON rawdata (status);

CREATE INDEX IF NOT EXISTS idx_rawdata_content_hash
    ON rawdata (raw_content_hash);

CREATE INDEX IF NOT EXISTS idx_rawdata_crawl_run_id
    ON rawdata (crawl_run_id);
