CREATE TABLE IF NOT EXISTS "sources" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "url" varchar UNIQUE NOT NULL,
  "source_type" varchar,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "raw_articles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "source_id" integer NOT NULL,
  "canonical_article_id" integer,
  "external_url" varchar NOT NULL,
  "title_raw" text,
  "content_raw" text,
  "author" varchar,
  "published_at" timestamp,
  "collected_at" timestamp DEFAULT (now()),
  "status" varchar
);

CREATE TABLE IF NOT EXISTS "categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "slug" varchar UNIQUE
);

CREATE TABLE IF NOT EXISTS "articles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" integer,
  "title" varchar NOT NULL,
  "slug" varchar UNIQUE,
  "content" text,
  "thumbnail_url" varchar,
  "summary" text,
  "key_points" text,
  "why_it_matters" text,
  "importance_score" float,
  "status" varchar,
  "published_at" timestamp,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE IF NOT EXISTS "entities" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "entity_type" varchar
);

CREATE TABLE IF NOT EXISTS "article_entities" (
  "article_id" integer,
  "entity_id" integer,
  PRIMARY KEY ("article_id", "entity_id")
);

CREATE TABLE IF NOT EXISTS "topics" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS "article_topics" (
  "article_id" integer,
  "topic_id" integer,
  PRIMARY KEY ("article_id", "topic_id")
);

CREATE TABLE IF NOT EXISTS "article_chunks" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "article_id" integer NOT NULL,
  "chunk_index" integer NOT NULL,
  "chunk_text" text NOT NULL,
  "vector_id" varchar,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "name" varchar,
  "created_at" timestamp DEFAULT (now()),
  "last_login_at" timestamp
);

CREATE TABLE IF NOT EXISTS "admins" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "name" varchar,
  "created_at" timestamp DEFAULT (now()),
  "last_login_at" timestamp
);

CREATE TABLE IF NOT EXISTS "conversations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "article_id" integer,
  "chat_type" varchar,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "messages" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conversation_id" integer NOT NULL,
  "sender_role" varchar,
  "content" text NOT NULL,
  "citations" text,
  "created_at" timestamp DEFAULT (now())
);

COMMENT ON COLUMN "sources"."name" IS 'Ten nguon: OpenAI Blog, DeepMind, arXiv, YouTube...';

COMMENT ON COLUMN "sources"."source_type" IS 'rss | api | crawler | social | academic';

COMMENT ON COLUMN "raw_articles"."canonical_article_id" IS 'Null cho toi khi duoc gom vao 1 ban ghi chuan';

COMMENT ON COLUMN "raw_articles"."external_url" IS 'URL bai goc, dung de doi chieu trung lap';

COMMENT ON COLUMN "raw_articles"."content_raw" IS 'Noi dung tho, chua qua xu ly';

COMMENT ON COLUMN "raw_articles"."status" IS 'pending | processed | duplicate';

COMMENT ON COLUMN "categories"."name" IS 'AI, Robotics, Research, Startup, Big Tech, Hardware';

COMMENT ON COLUMN "articles"."content" IS 'Noi dung goc da lam sach (boilerplate/HTML rac da bi loai)';

COMMENT ON COLUMN "articles"."thumbnail_url" IS 'Anh dai dien bai viet, hien thi o trang chu / danh sach bai viet';

COMMENT ON COLUMN "articles"."summary" IS 'Tom tat nhanh do AI sinh (Summarization)';

COMMENT ON COLUMN "articles"."key_points" IS 'JSON array - cac luan diem cot loi (Key Point Extraction)';

COMMENT ON COLUMN "articles"."why_it_matters" IS 'Phan tich boi canh / muc do anh huong (Impact Analysis)';

COMMENT ON COLUMN "articles"."importance_score" IS 'Diem quan trong do AI cham (Importance Scoring)';

COMMENT ON COLUMN "articles"."status" IS 'draft | published';

COMMENT ON COLUMN "entities"."name" IS 'Ten thuc the: OpenAI, Sam Altman, GPT-5...';

COMMENT ON COLUMN "entities"."entity_type" IS 'person | organization | product | technology';

COMMENT ON COLUMN "topics"."name" IS 'Chu de/su kien lon dung de gom nhieu bai lien quan';

COMMENT ON COLUMN "article_chunks"."chunk_index" IS 'Thu tu doan trong bai';

COMMENT ON COLUMN "article_chunks"."vector_id" IS 'ID tro toi vector tuong ung trong Qdrant/pgvector';

COMMENT ON COLUMN "conversations"."article_id" IS 'Null neu la Global News Chat';

COMMENT ON COLUMN "conversations"."chat_type" IS 'article_chat | global_chat';

COMMENT ON COLUMN "messages"."sender_role" IS 'user | assistant';

COMMENT ON COLUMN "messages"."citations" IS 'JSON array cac article_id duoc trich dan (RAG)';

ALTER TABLE "raw_articles" ADD FOREIGN KEY ("source_id") REFERENCES "sources" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "raw_articles" ADD FOREIGN KEY ("canonical_article_id") REFERENCES "articles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "articles" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "article_entities" ADD FOREIGN KEY ("article_id") REFERENCES "articles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "article_entities" ADD FOREIGN KEY ("entity_id") REFERENCES "entities" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "article_topics" ADD FOREIGN KEY ("article_id") REFERENCES "articles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "article_topics" ADD FOREIGN KEY ("topic_id") REFERENCES "topics" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "article_chunks" ADD FOREIGN KEY ("article_id") REFERENCES "articles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "conversations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "conversations" ADD FOREIGN KEY ("article_id") REFERENCES "articles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "messages" ADD FOREIGN KEY ("conversation_id") REFERENCES "conversations" ("id") DEFERRABLE INITIALLY IMMEDIATE;